# Site settings
title: Dev JeongSeungHyeon
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jeong SeungHyeon
user_description: “Perfectionists with Deadlines”  Developer
user_title: Software Developer
email: jshsakura@gmail.com
twitter_username: jshsakura
github_username:  jshsakura
gplus_username:  jshsakura

# Google-analytics
google-analytics:
  id: "jshsakura"

exclude: ['package.json', 'src' , 'node_modules']
